<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Metody przetwarzania i analizy danych w R - 3&nbsp; Klasyfikacja</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-regresja.html" rel="next">
<link href="./02-testy.html" rel="prev">
<link href="./favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03-klasyfikacja.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Klasyfikacja</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Metody przetwarzania i analizy danych w R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Wprowadzenie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Analiza opisowa</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-testy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Testowanie hipotez</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-klasyfikacja.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Klasyfikacja</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-regresja.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresja</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-grupowanie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Grupowanie</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Spis treści</h2>
   
  <ul>
  <li><a href="#wprowadzenie" id="toc-wprowadzenie" class="nav-link active" data-scroll-target="#wprowadzenie"><span class="header-section-number">3.1</span> Wprowadzenie</a></li>
  <li><a href="#drzewa-decyzyjne" id="toc-drzewa-decyzyjne" class="nav-link" data-scroll-target="#drzewa-decyzyjne"><span class="header-section-number">3.2</span> Drzewa decyzyjne</a></li>
  <li><a href="#gradient-boosting-machine" id="toc-gradient-boosting-machine" class="nav-link" data-scroll-target="#gradient-boosting-machine"><span class="header-section-number">3.3</span> Gradient Boosting Machine</a>
  <ul class="collapse">
  <li><a href="#zadania" id="toc-zadania" class="nav-link" data-scroll-target="#zadania"><span class="header-section-number">3.3.1</span> Zadania</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Klasyfikacja</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><a href="presentations/04_klasyfikacja.html">Prezentacja</a></p>
<section id="wprowadzenie" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="wprowadzenie"><span class="header-section-number">3.1</span> Wprowadzenie</h2>
<p>Celem analizy klasyfikacji jest zbudowanie modelu predykcyjnego, który w rezultacie zwróci prawdopodobieństwo przynależności danej obserwacji do jeden z dwóch klas. Przykładowo na podstawie danych o klientach banku można stworzyć model oceny zdolności kredytowej dla nowych klientów. W tym rozdziale posłużymy się <a href="https://archive.ics.uci.edu/ml/datasets/statlog+(german+credit+data)">German Credit Data</a> do budowy takiego predyktora. Wybrane kolumny z tego zbioru znajdują się w <a href="data/german_credit_data.xlsx">tym pliku</a>.</p>
<p>W pierwszym kroku wczytujemy dane i dokonujemy niezbędnych przekształceń tego zbioru. Z wykorzystaniem funkcji <code>clean_names()</code> z pakietu <em>janitor</em> zamieniamy nazwy kolumn w przyjazne przetwarzaniu przez komputer (brak spacji, polskich znaków, itp.). Następnie zmienne tekstowe zamieniamy na zmienne jakościowe - faktory oraz tworzymy nową kolumnę zawierającą wysokość raty kredytu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>credit <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/german_credit_data.xlsx"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.character, as.factor) <span class="sc">%&gt;%</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">job=</span><span class="fu">as.factor</span>(job),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">installment=</span>credit_amount<span class="sc">/</span>duration)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(credit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age            sex      job     housing      saving_accounts
 Min.   :19.00   female:310   0: 22   free:108   little    :603   
 1st Qu.:27.00   male  :690   1:200   own :713   moderate  :103   
 Median :33.00                2:630   rent:179   quite rich: 63   
 Mean   :35.55                3:148              rich      : 48   
 3rd Qu.:42.00                                   NA's      :183   
 Max.   :75.00                                                    
                                                                  
 checking_account credit_amount      duration                   purpose   
 little  :274     Min.   :  250   Min.   : 4.0   car                :337  
 moderate:269     1st Qu.: 1366   1st Qu.:12.0   radio/TV           :280  
 rich    : 63     Median : 2320   Median :18.0   furniture/equipment:181  
 NA's    :394     Mean   : 3271   Mean   :20.9   business           : 97  
                  3rd Qu.: 3972   3rd Qu.:24.0   education          : 59  
                  Max.   :18424   Max.   :72.0   repairs            : 22  
                                                 (Other)            : 24  
   risk      installment     
 bad :300   Min.   :  24.06  
 good:700   1st Qu.:  89.60  
            Median : 130.33  
            Mean   : 167.69  
            3rd Qu.: 206.18  
            Max.   :2482.67  
                             </code></pre>
</div>
</div>
<p>Zamiana cech tekstowych na faktory pozwala w podsumowaniu wygenerowanym przez funkcję <code>summary()</code> obserwować od razu częstości poszczególnych wariantów. Możemy zaobserwować występowanie braków danych w zmiennych saving accounts i checking_account. Generalnie jest to zbyt duży problem, bo tylko niektóre algorytmy klasyfikacji nie obsługują braków danych w zmiennych objaśniających. Ważne jest, żeby braki danych nie występowały dla cechy decyzyjnej.</p>
<p>Obserwacje z brakami danych można usunąć, ale często spowodowałoby to znaczne zmniejszenie próby badawczej, zatem stosuje się metody mające na celu uzupełnienie braków danych. W najprostszym przypadku braki można zastąpić średnią, medianą lub dominantą. Do bardziej zaawansowanych sposobów należy metoda najbliższych sąsiadów (<a href="https://cran.r-project.org/web/packages/VIM/index.html">VIM</a>) albo imputacja wielokrotna (<a href="https://cran.r-project.org/web/packages/mice/index.html">mice</a>).</p>
<p>W omawianym przypadku klientów wiarygodnych jest 700, a tych, którzy nie spłacili zobowiązania 300. Mamy zatem do czynienia z niezbalansowaną próbą. W idealnym przypadku klasyfikacji, przypadków z każdej grupy powinno być tyle samo. W przeciwnym przypadku model będzie działał lepiej dla klasy większościowej. Najprostszą metodą balansowania danych jest upsampling czyli dolosowywanie obserwacji z klasy mniejszościowej, tak aby wyrównać liczebności. Przeciwieństwem tego podejścia jest downsampling. Alternatywnie można zastosować metodę SMOTE, która generuje sztuczne obserwacje dla klasy mniejszościowej (pakiety <a href="https://cran.r-project.org/web/packages/DMwR/index.html">DMwR</a>, <a href="https://cran.r-project.org/web/packages/imbalance/index.html">imbalance</a>).</p>
</section>
<section id="drzewa-decyzyjne" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="drzewa-decyzyjne"><span class="header-section-number">3.2</span> Drzewa decyzyjne</h2>
<p>Najpopularniejszą metodą klasyfikacji są drzewa decyzyjne, które charakteryzują się z reguły dobrą efektywnością i pozwalają na łatwą interpretację zastosowanych reguł klasyfikacji. Wykorzystamy pakiet <a href="https://cran.r-project.org/web/packages/rpart/index.html">rpart</a> do stworzenia drzewa oraz pakiet <a href="https://cran.r-project.org/web/packages/rpart.plot/index.html">rpart.plot</a> do wizualizacji.</p>
<p>Proces tworzenia drzewa jest bardzo prosty, a argumenty w funkcji <code>rpart()</code> są takie same jak w regresji liniowej.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'rpart' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'rpart.plot' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">rpart</span>(<span class="at">formula =</span> risk <span class="sc">~</span> ., <span class="at">data =</span> credit)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-klasyfikacja_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>W rezultacie uzyskujemy drzewo decyzyjne z optymalnie dobranymi zmiennymi objaśniającymi. W każdym węźle drzewa podane są następujące wartości: - prognozowana klasa, prawdopodobieństwa zaklasyfikowania do klasy pozytywnej, odsetek obserwacji w węźle. Domyślnym progiem klasyfikacji jest wartość 0,5. Jeżeli prawdopodobieństwo jest poniżej tej wartości to nastąpi przypisanie do grupy klientów niespłacających pożyczki, a jeśli powyżej to do tej drugiej grupy.</p>
<p>Oceny jakości klasyfikatora dokonuje się na podstawie <a href="https://pl.wikipedia.org/wiki/Tablica_pomy%C5%82ek">macierzy pomyłek</a> oraz miar wyznaczonych na jej podstawie. Najpopularniejsze z nich to:</p>
<ul>
<li>dokładność (accuracy): % poprawnie zaklasyfikowanych</li>
<li>precyzja (precison): % poprawnie rozpoznanych przypadków pozytywnych TP/(TP+FP)</li>
<li>czułość (sensitivity/recall): % prawdziwie pozytywnych TP/(TP+FN)</li>
<li>swoistość (specificity): % prawdziwie negatywnych TN/(TN+FP)</li>
<li>F1: średnia harmoniczna z czułości i precyzji 2TP/(2TP+FP+FN)</li>
</ul>
<p>Im wyższe wartości tych miar tym lepszy klasyfikator. Do wyznaczenia tych miar w R służy funkcja z pakietu <a href="https://topepo.github.io/caret/">caret</a>. W tym celu trzeba wyznaczyć wartości prognozowanej klasy na podstawie modelu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'caret' was built under R version 4.3.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'caret'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    lift</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>pred_risk_m1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="at">object =</span> m1, <span class="at">newdata =</span> credit, <span class="at">type =</span> <span class="st">"class"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Argument <code>type</code> określa typ predykcji: <code>"class"</code> oznacza prognozowaną klasę, a <code>"prob"</code> prawdopodobieństwo. Na tej podstawie oraz wartości rzeczywistych tworzymy macierz pomyłek:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> pred_risk_m1, <span class="at">reference =</span> credit<span class="sc">$</span>risk, </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">positive =</span> <span class="st">"good"</span>, <span class="at">mode =</span> <span class="st">"everything"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction bad good
      bad  117   60
      good 183  640
                                          
               Accuracy : 0.757           
                 95% CI : (0.7292, 0.7833)
    No Information Rate : 0.7             
    P-Value [Acc &gt; NIR] : 3.553e-05       
                                          
                  Kappa : 0.3447          
                                          
 Mcnemar's Test P-Value : 5.024e-15       
                                          
            Sensitivity : 0.9143          
            Specificity : 0.3900          
         Pos Pred Value : 0.7776          
         Neg Pred Value : 0.6610          
              Precision : 0.7776          
                 Recall : 0.9143          
                     F1 : 0.8404          
             Prevalence : 0.7000          
         Detection Rate : 0.6400          
   Detection Prevalence : 0.8230          
      Balanced Accuracy : 0.6521          
                                          
       'Positive' Class : good            
                                          </code></pre>
</div>
</div>
<p>W naszym przykładzie spośród 1000 klientów, model jako wiarygodnych kredytobiorców zaklasyfikował 640, a 117 prawidłowo jako osoby, które nie spłaciły zobowiązania. W 60 przypadkach model uznał brak zdolności kredytowej u klienta, podczas gdy w rzeczywistości pożyczka została spłacona. Dla 183 klientów podjętoby odwrotną decyzję - model przyznałby kredyt, a w rzeczywistości osoby te nie spłaciły pożyczki. Dokładność w tym przypadku wynosi 75,7%, a precyzja 77,8%. Czułość tego predyktora jest wysoka (91,4%), ale swoistość już nie (39%), na co może mieć wpływ niezbalansowanie danych.</p>
<p>Przedstawiony powyżej przykład miał charakter analizy ekspolarycyjnej - opartej na całym zbiorze danych. W praktyce stosuje się podejście polegające na podziale zbioru danych na zbiór treningowy oraz walidacyjny. Na danych ze zbioru treningowego buduje się model, który następnie testowany jest na danych, których nigdy wcześniej “nie widział” - na zbiorze walidacyjnym. Miary klasyfikacji obliczone na podstawie zbioru walidacyjnego dostarczają realnej oceny jakości klasyfikatora.</p>
<p>Do podziału zbioru służy funkcja <code>createDataPartition()</code> z pakietu <em>caret</em>. Zbiory treningowy i walidacyjny tworzone są w taki sposób, aby zachować proporcje w zmiennej decyzyjnej. Domyślnie funkcja dzieli zbiór danych w układzie 50/50, natomiast w tym przykładzie 80% obserwacji umieścimy w zbiorze treningowym.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>split <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(<span class="at">y =</span> credit<span class="sc">$</span>risk, <span class="at">p =</span> <span class="fl">0.8</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>train_credit <span class="ot">&lt;-</span> credit[split<span class="sc">$</span>Resample1,]</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>valid_credit <span class="ot">&lt;-</span> credit[<span class="sc">-</span>split<span class="sc">$</span>Resample1,]</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(train_credit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age            sex      job     housing      saving_accounts
 Min.   :19.00   female:252   0: 17   free: 80   little    :486   
 1st Qu.:27.00   male  :548   1:159   own :576   moderate  : 85   
 Median :33.00                2:504   rent:144   quite rich: 49   
 Mean   :35.43                3:120              rich      : 34   
 3rd Qu.:42.00                                   NA's      :146   
 Max.   :75.00                                                    
                                                                  
 checking_account credit_amount      duration                    purpose   
 little  :228     Min.   :  276   Min.   : 4.00   car                :284  
 moderate:205     1st Qu.: 1374   1st Qu.:12.00   radio/TV           :219  
 rich    : 46     Median : 2326   Median :18.00   furniture/equipment:139  
 NA's    :321     Mean   : 3300   Mean   :21.02   business           : 76  
                  3rd Qu.: 3965   3rd Qu.:24.00   education          : 46  
                  Max.   :18424   Max.   :72.00   repairs            : 17  
                                                  (Other)            : 19  
   risk      installment     
 bad :240   Min.   :  24.06  
 good:560   1st Qu.:  87.18  
            Median : 131.74  
            Mean   : 168.95  
            3rd Qu.: 206.06  
            Max.   :2482.67  
                             </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(valid_credit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age            sex      job     housing      saving_accounts
 Min.   :20.00   female: 58   0:  5   free: 28   little    :117   
 1st Qu.:27.00   male  :142   1: 41   own :137   moderate  : 18   
 Median :34.00                2:126   rent: 35   quite rich: 14   
 Mean   :36.02                3: 28              rich      : 14   
 3rd Qu.:42.00                                   NA's      : 37   
 Max.   :74.00                                                    
                                                                  
 checking_account credit_amount      duration                    purpose  
 little  :46      Min.   :  250   Min.   : 4.00   radio/TV           :61  
 moderate:64      1st Qu.: 1308   1st Qu.:12.00   car                :53  
 rich    :17      Median : 2261   Median :18.00   furniture/equipment:42  
 NA's    :73      Mean   : 3157   Mean   :20.43   business           :21  
                  3rd Qu.: 4003   3rd Qu.:24.00   education          :13  
                  Max.   :15672   Max.   :48.00   repairs            : 5  
                                                  (Other)            : 5  
   risk      installment    
 bad : 60   Min.   : 38.12  
 good:140   1st Qu.: 93.12  
            Median :127.23  
            Mean   :162.62  
            3rd Qu.:206.21  
            Max.   :730.80  
                            </code></pre>
</div>
</div>
<p>Wykorzystując tak przygotowane dane możemy jeszcze raz wykorzystać drzewa decyzyjne do stworzenia klasyfikatora, ale tym razem wyłącznie na zbiorze treningowym.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">rpart</span>(risk <span class="sc">~</span> ., train_credit)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-klasyfikacja_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Utworzone drzewo będzie różnić się od tego, które powstało na podstawie całego zbioru danych. Następnie obliczamy prognozowane klasy na obu zbiorach i wyznaczamy macierze pomyłek.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>pred_risk_m2_train <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="at">object =</span> m2, <span class="at">newdata =</span> train_credit, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>pred_risk_m2_valid <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="at">object =</span> m2, <span class="at">newdata =</span> valid_credit, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># train</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> pred_risk_m2_train, <span class="at">reference =</span> train_credit<span class="sc">$</span>risk, </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">positive =</span> <span class="st">"good"</span>, <span class="at">mode =</span> <span class="st">"everything"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction bad good
      bad   94   38
      good 146  522
                                          
               Accuracy : 0.77            
                 95% CI : (0.7392, 0.7987)
    No Information Rate : 0.7             
    P-Value [Acc &gt; NIR] : 5.783e-06       
                                          
                  Kappa : 0.3716          
                                          
 Mcnemar's Test P-Value : 3.067e-15       
                                          
            Sensitivity : 0.9321          
            Specificity : 0.3917          
         Pos Pred Value : 0.7814          
         Neg Pred Value : 0.7121          
              Precision : 0.7814          
                 Recall : 0.9321          
                     F1 : 0.8502          
             Prevalence : 0.7000          
         Detection Rate : 0.6525          
   Detection Prevalence : 0.8350          
      Balanced Accuracy : 0.6619          
                                          
       'Positive' Class : good            
                                          </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># valid</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> pred_risk_m2_valid, <span class="at">reference =</span> valid_credit<span class="sc">$</span>risk, </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">positive =</span> <span class="st">"good"</span>, <span class="at">mode =</span> <span class="st">"everything"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction bad good
      bad   18   11
      good  42  129
                                          
               Accuracy : 0.735           
                 95% CI : (0.6681, 0.7948)
    No Information Rate : 0.7             
    P-Value [Acc &gt; NIR] : 0.1579          
                                          
                  Kappa : 0.2598          
                                          
 Mcnemar's Test P-Value : 3.775e-05       
                                          
            Sensitivity : 0.9214          
            Specificity : 0.3000          
         Pos Pred Value : 0.7544          
         Neg Pred Value : 0.6207          
              Precision : 0.7544          
                 Recall : 0.9214          
                     F1 : 0.8296          
             Prevalence : 0.7000          
         Detection Rate : 0.6450          
   Detection Prevalence : 0.8550          
      Balanced Accuracy : 0.6107          
                                          
       'Positive' Class : good            
                                          </code></pre>
</div>
</div>
<p>Generalnie wyniki w obu przypadkach powinny być do siebie zbliżone, przy czym na zbiorze walidacyjnym miary jakości predycji mogą być trochę gorsze. Bardzo wysoka wartość dokładność na zbiorze treningowym, a niska na zbiorze walidacyjnym jest symptomem przeuczenia modelu - algorytm nauczył się odpowiedzi “na pamięć”.</p>
</section>
<section id="gradient-boosting-machine" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="gradient-boosting-machine"><span class="header-section-number">3.3</span> Gradient Boosting Machine</h2>
<p>Spróbujemy polepszyć jakość klasyfikacji z wykorzystaniem metody gradient boostingu. W tym celu wykorzystamy pakiet <a href="https://www.h2o.ai/">h2o</a>, który dostarcza kompleksowych rozwiązań z zakresu machine learning. W pierwszej kolejności trzeba zmienić format danych na ten obsługiwany przez pakiet.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(h2o)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
----------------------------------------------------------------------

Your next step is to start H2O:
    &gt; h2o.init()

For H2O package documentation, ask for help:
    &gt; ??h2o

After starting H2O, you can use the Web UI at http://localhost:54321
For more information visit https://docs.h2o.ai

----------------------------------------------------------------------</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'h2o'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:lubridate':

    day, hour, month, week, year</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    cor, sd, var</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    %*%, %in%, &amp;&amp;, ||, apply, as.factor, as.numeric, colnames,
    colnames&lt;-, ifelse, is.character, is.factor, is.numeric, log,
    log10, log1p, log2, round, signif, trunc</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">h2o.init</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
H2O is not running yet, starting it now...

Note:  In case of errors look at the following log files:
    C:\Users\lukas\AppData\Local\Temp\RtmpekkK39\file2a8812393c3/h2o_lukas_started_from_r.out
    C:\Users\lukas\AppData\Local\Temp\RtmpekkK39\file2a8816c87bf/h2o_lukas_started_from_r.err


Starting H2O JVM and connecting: . Connection successful!

R is connected to the H2O cluster: 
    H2O cluster uptime:         5 seconds 833 milliseconds 
    H2O cluster timezone:       Europe/Belgrade 
    H2O data parsing timezone:  UTC 
    H2O cluster version:        3.42.0.2 
    H2O cluster version age:    10 months and 28 days 
    H2O cluster name:           H2O_started_from_R_lukas_xpm862 
    H2O cluster total nodes:    1 
    H2O cluster total memory:   3.52 GB 
    H2O cluster total cores:    8 
    H2O cluster allowed cores:  8 
    H2O cluster healthy:        TRUE 
    H2O Connection ip:          localhost 
    H2O Connection port:        54321 
    H2O Connection proxy:       NA 
    H2O Internal Security:      FALSE 
    R Version:                  R version 4.3.2 (2023-10-31 ucrt) </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in h2o.clusterInfo(): 
Your H2O cluster version is (10 months and 28 days) old. There may be a newer version available.
Please download and install the latest version from: https://h2o-release.s3.amazonaws.com/h2o/latest_stable.html</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">h2o.no_progress</span>() <span class="co"># brak pasków postępu</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>train_credit_h2o <span class="ot">&lt;-</span> <span class="fu">as.h2o</span>(train_credit)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>valid_credit_h2o <span class="ot">&lt;-</span> <span class="fu">as.h2o</span>(valid_credit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Następnie deklarujemy nazwy wykorzystywanych zmiennych i uruchamiamy procedurę:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>y_var <span class="ot">&lt;-</span> <span class="st">"risk"</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>x_var <span class="ot">&lt;-</span> <span class="fu">names</span>(credit)[<span class="sc">-</span><span class="dv">10</span>]</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">h2o.gbm</span>(<span class="at">x =</span> x_var, </span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">y =</span> y_var, </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">training_frame =</span> train_credit_h2o, </span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">validation_frame =</span> valid_credit_h2o, </span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">seed =</span> <span class="dv">1</span>)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>m3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model Details:
==============

H2OBinomialModel: gbm
Model ID:  GBM_model_R_1719054914797_1 
Model Summary: 
  number_of_trees number_of_internal_trees model_size_in_bytes min_depth
1              50                       50               13762         5
  max_depth mean_depth min_leaves max_leaves mean_leaves
1         5    5.00000         10         26    17.38000


H2OBinomialMetrics: gbm
** Reported on training data. **

MSE:  0.07844172
RMSE:  0.2800745
LogLoss:  0.2801827
Mean Per-Class Error:  0.09345238
AUC:  0.9696838
AUCPR:  0.9855312
Gini:  0.9393676
R^2:  0.626468

Confusion Matrix (vertical: actual; across: predicted) for F1-optimal threshold:
       bad good    Error     Rate
bad    205   35 0.145833  =35/240
good    23  537 0.041071  =23/560
Totals 228  572 0.072500  =58/800

Maximum Metrics: Maximum metrics at their respective thresholds
                        metric threshold      value idx
1                       max f1  0.569359   0.948763 236
2                       max f2  0.478467   0.964236 262
3                 max f0point5  0.669186   0.948864 201
4                 max accuracy  0.569359   0.927500 236
5                max precision  0.987622   1.000000   0
6                   max recall  0.363744   1.000000 305
7              max specificity  0.987622   1.000000   0
8             max absolute_mcc  0.569359   0.825421 236
9   max min_per_class_accuracy  0.651784   0.904167 206
10 max mean_per_class_accuracy  0.669186   0.907738 201
11                     max tns  0.987622 240.000000   0
12                     max fns  0.987622 559.000000   0
13                     max fps  0.049138 240.000000 399
14                     max tps  0.363744 560.000000 305
15                     max tnr  0.987622   1.000000   0
16                     max fnr  0.987622   0.998214   0
17                     max fpr  0.049138   1.000000 399
18                     max tpr  0.363744   1.000000 305

Gains/Lift Table: Extract with `h2o.gainsLift(&lt;model&gt;, &lt;data&gt;)` or `h2o.gainsLift(&lt;model&gt;, valid=&lt;T/F&gt;, xval=&lt;T/F&gt;)`
H2OBinomialMetrics: gbm
** Reported on validation data. **

MSE:  0.1816324
RMSE:  0.4261836
LogLoss:  0.5493537
Mean Per-Class Error:  0.4071429
AUC:  0.729881
AUCPR:  0.8518075
Gini:  0.4597619
R^2:  0.1350837

Confusion Matrix (vertical: actual; across: predicted) for F1-optimal threshold:
       bad good    Error     Rate
bad     12   48 0.800000   =48/60
good     2  138 0.014286   =2/140
Totals  14  186 0.250000  =50/200

Maximum Metrics: Maximum metrics at their respective thresholds
                        metric threshold      value idx
1                       max f1  0.288120   0.846626 185
2                       max f2  0.195621   0.928382 193
3                 max f0point5  0.587924   0.809659 140
4                 max accuracy  0.289167   0.750000 183
5                max precision  0.973438   1.000000   0
6                   max recall  0.195621   1.000000 193
7              max specificity  0.973438   1.000000   0
8             max absolute_mcc  0.587924   0.366055 140
9   max min_per_class_accuracy  0.738988   0.685714 113
10 max mean_per_class_accuracy  0.738988   0.692857 113
11                     max tns  0.973438  60.000000   0
12                     max fns  0.973438 139.000000   0
13                     max fps  0.067249  60.000000 199
14                     max tps  0.195621 140.000000 193
15                     max tnr  0.973438   1.000000   0
16                     max fnr  0.973438   0.992857   0
17                     max fpr  0.067249   1.000000 199
18                     max tpr  0.195621   1.000000 193

Gains/Lift Table: Extract with `h2o.gainsLift(&lt;model&gt;, &lt;data&gt;)` or `h2o.gainsLift(&lt;model&gt;, valid=&lt;T/F&gt;, xval=&lt;T/F&gt;)`</code></pre>
</div>
</div>
<p>Z funkcji pakietu h2o dostajemy pokaźny wydruk podsumowania klasyfikacji wraz z macierzami pomyłek. Pakiet h2o optymalizuje jakość predycji maksymalizująć miarę F1 - średnią harmoniczną czułości i swoistości. Zatem w tym przypadku podział na klasy wg prawdopodobieństwa nie odbywa się już na podstawie wartości 0,5.</p>
<p>Stworzymy macierz pomyłek dla zbioru walidacyjnego w tym samym formacie, co wcześniej:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>pred_risk_m3_valid <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">h2o.predict</span>(<span class="at">object =</span> m3, <span class="at">newdata =</span> valid_credit_h2o))</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> pred_risk_m3_valid<span class="sc">$</span>predict, <span class="at">reference =</span> valid_credit<span class="sc">$</span>risk, </span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">positive =</span> <span class="st">"good"</span>, <span class="at">mode =</span> <span class="st">"everything"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction bad good
      bad   12    2
      good  48  138
                                         
               Accuracy : 0.75           
                 95% CI : (0.684, 0.8084)
    No Information Rate : 0.7            
    P-Value [Acc &gt; NIR] : 0.06955        
                                         
                  Kappa : 0.2378         
                                         
 Mcnemar's Test P-Value : 1.966e-10      
                                         
            Sensitivity : 0.9857         
            Specificity : 0.2000         
         Pos Pred Value : 0.7419         
         Neg Pred Value : 0.8571         
              Precision : 0.7419         
                 Recall : 0.9857         
                     F1 : 0.8466         
             Prevalence : 0.7000         
         Detection Rate : 0.6900         
   Detection Prevalence : 0.9300         
      Balanced Accuracy : 0.5929         
                                         
       'Positive' Class : good           
                                         </code></pre>
</div>
</div>
<p>Możemy zauważyć nieznaczną poprawę dokładności predykcji w porównaniu do drzewa decyzyjnego - z 73,5% do 75%. Natomiast ten algorytm został uruchomiony z domyślnymi parametrami i być może wybór innych wartości mógłby poprawić jakość predykcji. Poszukiwania najlepszych wartości do algorytmu nosi nazwę tuningu hiperparametrów. Z racji tego, że przeszukiwana przestrzeń parametrów mogłaby być bardzo duża to z reguły przeprowadza się to w sposób losowy. Poniżej lista możliwych do zastosowania parametrów w metodzie GBM.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>gbm_params <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">learn_rate =</span> <span class="fu">seq</span>(<span class="fl">0.01</span>, <span class="fl">0.1</span>, <span class="fl">0.01</span>),</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">max_depth =</span> <span class="fu">seq</span>(<span class="dv">2</span>, <span class="dv">10</span>, <span class="dv">1</span>),</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">sample_rate =</span> <span class="fu">seq</span>(<span class="fl">0.5</span>, <span class="fl">1.0</span>, <span class="fl">0.1</span>),</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">col_sample_rate =</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="fl">1.0</span>, <span class="fl">0.1</span>),</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ntrees =</span> <span class="fu">seq</span>(<span class="dv">50</span>,<span class="dv">150</span>,<span class="dv">10</span>))</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>search_criteria <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">strategy =</span> <span class="st">"RandomDiscrete"</span>, <span class="at">max_models =</span> <span class="dv">36</span>, <span class="at">seed =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wszystkich kombinacji parametrów jest 59400 i weryfikacja ich wszystkich zajęła by sporo czasu, zatem w sposób losowy szukamy najlepszych 36 modeli. Z tego zestawu wybieramy najlepszy według kryterium jakim jest miara AUC.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>gbm_grid <span class="ot">&lt;-</span> <span class="fu">h2o.grid</span>(<span class="at">algorithm =</span> <span class="st">"gbm"</span>, </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">x =</span> x_var, </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> y_var,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">grid_id =</span> <span class="st">"gbm_grid"</span>,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">training_frame =</span> train_credit_h2o,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">validation_frame =</span> valid_credit_h2o,</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">seed =</span> <span class="dv">1</span>,</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">hyper_params =</span> gbm_params,</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">search_criteria =</span> search_criteria)</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>gbm_gridperf <span class="ot">&lt;-</span> <span class="fu">h2o.getGrid</span>(<span class="at">grid_id =</span> <span class="st">"gbm_grid"</span>,</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>                            <span class="at">sort_by =</span> <span class="st">"auc"</span>,</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>                            <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">h2o.getModel</span>(gbm_gridperf<span class="sc">@</span>model_ids[[<span class="dv">1</span>]])</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>m4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model Details:
==============

H2OBinomialModel: gbm
Model ID:  gbm_grid_model_33 
Model Summary: 
  number_of_trees number_of_internal_trees model_size_in_bytes min_depth
1              80                       80                8424         2
  max_depth mean_depth min_leaves max_leaves mean_leaves
1         2    2.00000          3          4     3.75000


H2OBinomialMetrics: gbm
** Reported on training data. **

MSE:  0.1442394
RMSE:  0.3797886
LogLoss:  0.449481
Mean Per-Class Error:  0.2833333
AUC:  0.8456138
AUCPR:  0.921934
Gini:  0.6912277
R^2:  0.3131457

Confusion Matrix (vertical: actual; across: predicted) for F1-optimal threshold:
       bad good    Error      Rate
bad    119  121 0.504167  =121/240
good    35  525 0.062500   =35/560
Totals 154  646 0.195000  =156/800

Maximum Metrics: Maximum metrics at their respective thresholds
                        metric threshold      value idx
1                       max f1  0.500182   0.870647 293
2                       max f2  0.371147   0.932146 352
3                 max f0point5  0.671700   0.864148 196
4                 max accuracy  0.500182   0.805000 293
5                max precision  0.956594   1.000000   0
6                   max recall  0.292273   1.000000 379
7              max specificity  0.956594   1.000000   0
8             max absolute_mcc  0.643739   0.520541 214
9   max min_per_class_accuracy  0.666048   0.770833 200
10 max mean_per_class_accuracy  0.671700   0.775595 196
11                     max tns  0.956594 240.000000   0
12                     max fns  0.956594 559.000000   0
13                     max fps  0.163448 240.000000 399
14                     max tps  0.292273 560.000000 379
15                     max tnr  0.956594   1.000000   0
16                     max fnr  0.956594   0.998214   0
17                     max fpr  0.163448   1.000000 399
18                     max tpr  0.292273   1.000000 379

Gains/Lift Table: Extract with `h2o.gainsLift(&lt;model&gt;, &lt;data&gt;)` or `h2o.gainsLift(&lt;model&gt;, valid=&lt;T/F&gt;, xval=&lt;T/F&gt;)`
H2OBinomialMetrics: gbm
** Reported on validation data. **

MSE:  0.1749705
RMSE:  0.4182947
LogLoss:  0.5266207
Mean Per-Class Error:  0.4154762
AUC:  0.751369
AUCPR:  0.8703734
Gini:  0.5027381
R^2:  0.1668073

Confusion Matrix (vertical: actual; across: predicted) for F1-optimal threshold:
       bad good    Error     Rate
bad     11   49 0.816667   =49/60
good     2  138 0.014286   =2/140
Totals  13  187 0.255000  =51/200

Maximum Metrics: Maximum metrics at their respective thresholds
                        metric threshold      value idx
1                       max f1  0.399730   0.844037 178
2                       max f2  0.335934   0.925926 187
3                 max f0point5  0.624918   0.826023 127
4                 max accuracy  0.576083   0.760000 137
5                max precision  0.953756   1.000000   0
6                   max recall  0.335934   1.000000 187
7              max specificity  0.953756   1.000000   0
8             max absolute_mcc  0.624918   0.416343 127
9   max min_per_class_accuracy  0.696832   0.664286 105
10 max mean_per_class_accuracy  0.624918   0.711905 127
11                     max tns  0.953756  60.000000   0
12                     max fns  0.953756 139.000000   0
13                     max fps  0.247891  60.000000 191
14                     max tps  0.335934 140.000000 187
15                     max tnr  0.953756   1.000000   0
16                     max fnr  0.953756   0.992857   0
17                     max fpr  0.247891   1.000000 191
18                     max tpr  0.335934   1.000000 187

Gains/Lift Table: Extract with `h2o.gainsLift(&lt;model&gt;, &lt;data&gt;)` or `h2o.gainsLift(&lt;model&gt;, valid=&lt;T/F&gt;, xval=&lt;T/F&gt;)`</code></pre>
</div>
</div>
<p>Standardowo utworzymy macierz pomyłek i obliczymy pozostałe miary:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>pred_risk_m4_valid <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">h2o.predict</span>(<span class="at">object =</span> m4, <span class="at">newdata =</span> valid_credit_h2o))</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(<span class="at">data =</span> pred_risk_m4_valid<span class="sc">$</span>predict, <span class="at">reference =</span> valid_credit<span class="sc">$</span>risk, </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">positive =</span> <span class="st">"good"</span>, <span class="at">mode =</span> <span class="st">"everything"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction bad good
      bad   11    2
      good  49  138
                                          
               Accuracy : 0.745           
                 95% CI : (0.6787, 0.8039)
    No Information Rate : 0.7             
    P-Value [Acc &gt; NIR] : 0.09344         
                                          
                  Kappa : 0.2178          
                                          
 Mcnemar's Test P-Value : 1.185e-10       
                                          
            Sensitivity : 0.9857          
            Specificity : 0.1833          
         Pos Pred Value : 0.7380          
         Neg Pred Value : 0.8462          
              Precision : 0.7380          
                 Recall : 0.9857          
                     F1 : 0.8440          
             Prevalence : 0.7000          
         Detection Rate : 0.6900          
   Detection Prevalence : 0.9350          
      Balanced Accuracy : 0.5845          
                                          
       'Positive' Class : good            
                                          </code></pre>
</div>
</div>
<p>Finalny model charakteryzuje się dokładnością na poziomie 76,5%, zatem udało się poprawić jego jakość w porównaniu do drzewa decyzyjnego oraz wersji GBM z domyślnymi parametrami.</p>
<p>Innym sposobem oceny jakości modelu jest symulacja wyniku biznesowego na podstawie kosztów dla każdej komórki macierzy pomyłek. W naszym przypadku przyjmiemy bardzo uproszczone miary: średnia kwota kredytu: 3500, marża na spłaconym kredycie: 20%, strata na niespłaconym kredycie: 50%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># m2</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="dv">42</span><span class="sc">*-</span>(<span class="dv">3500</span><span class="sc">*</span><span class="fl">0.5</span>)<span class="sc">+</span><span class="dv">129</span><span class="sc">*</span>(<span class="dv">3500</span><span class="sc">*</span><span class="fl">0.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16800</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># m3</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="dv">50</span><span class="sc">*-</span>(<span class="dv">3500</span><span class="sc">*</span><span class="fl">0.5</span>)<span class="sc">+</span><span class="dv">140</span><span class="sc">*</span>(<span class="dv">3500</span><span class="sc">*</span><span class="fl">0.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10500</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># m4</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="dv">43</span><span class="sc">*-</span>(<span class="dv">3500</span><span class="sc">*</span><span class="fl">0.5</span>)<span class="sc">+</span><span class="dv">136</span><span class="sc">*</span>(<span class="dv">3500</span><span class="sc">*</span><span class="fl">0.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19950</code></pre>
</div>
</div>
<p>Największą korzyść uzyskamy korzystając z modelu <code>m4</code>.</p>
<p>Jakość predykcji możemy także spróbować poprawić manewrując progiem prawdopodobieństwa klasyfikacji. Narzędziem, które może w tym pomóc jest krzywa ROC, która przestawia wartości czułości i swoistości dla różnych progów.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">h2o.performance</span>(m4, <span class="at">valid =</span> T), <span class="at">type =</span> <span class="st">"roc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-klasyfikacja_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Przekątna przedstawia klasyfikator losowy, natomiast punkty leżące powyżej to klasyfikatory lepsze od losowego. Klasyfikator idealny byłby krzywą o następującym przebiegu (0,0) -&gt; (0,1) -&gt; (1,1). Pole pod krzywą ROC jest także miarą jakości klasyfikacji - AUC, której wysokie wartości są pożądane.</p>
<p>Zastosowany przez nas model GBM jest pewną czarną skrzynką, zatem nie wiadomo dokładnie na podstawie jakich reguł ta klasyfikacja przebiega, ale możemy wykorzystać pewne miary tzw. Explainable AI w celu opisu modelu.</p>
<p>Pierwszą z nich jest ważność cech, która określa jak bardzo model wykorzystuje daną cechę do predycji.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">h2o.varimp</span>(m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Variable Importances: 
           variable relative_importance scaled_importance percentage
1  checking_account          164.028534          1.000000   0.428749
2          duration           53.408806          0.325607   0.139603
3       installment           43.910915          0.267703   0.114777
4   saving_accounts           37.021275          0.225700   0.096769
5     credit_amount           35.085529          0.213899   0.091709
6               age           19.486319          0.118798   0.050935
7           purpose           15.291790          0.093226   0.039971
8               sex           10.269917          0.062611   0.026844
9           housing            2.307869          0.014070   0.006032
10              job            1.764029          0.010754   0.004611</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">h2o.varimp_plot</span>(m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-klasyfikacja_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Na tej podstawie możemy stwierdzić, że najważniejszą cechą mającą wpływ na klasyfikację jest checking_account. Na kolejnych miejscach jest installment oraz credit_amount. Najmniej ważna jest zmienna housing.</p>
<p>Innym metodem opisu działania modelu jest partial dependency plot, przedstawiający zależność prawdopodobieństwa klasyfikacji od wartości danej cechy niezależnej.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">h2o.partialPlot</span>(<span class="at">object =</span> m4, <span class="at">data =</span> valid_credit_h2o, <span class="at">cols =</span> <span class="fu">c</span>(<span class="st">"checking_account"</span>,<span class="st">"credit_amount"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-klasyfikacja_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "medcol" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "medlty" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "staplelty" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "boxlty" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "medcol" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "medlty" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "staplelty" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "boxlty" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "medcol" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "medlty" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "staplelty" is not
a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "boxlty" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "medcol" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "medlty" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "staplelty" is not
a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "boxlty" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in box(...): "medcol" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in box(...): "medlty" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in box(...): "staplelty" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in box(...): "boxlty" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "medcol" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "medlty" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "staplelty" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "boxlty" is not a graphical parameter</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03-klasyfikacja_files/figure-html/unnamed-chunk-17-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
PartialDependence: Partial dependency plot for checking_account
  checking_account mean_response stddev_response std_error_mean_response
1           little      0.591274        0.152221                0.010764
2         moderate      0.638785        0.150663                0.010654
3             rich      0.809393        0.092115                0.006514

[[2]]
PartialDependence: Partial dependency plot for credit_amount
   credit_amount mean_response stddev_response std_error_mean_response
1     250.000000      0.763155        0.157128                0.011111
2    1061.684211      0.722067        0.177397                0.012544
3    1873.368421      0.726639        0.179054                0.012661
4    2685.052632      0.726639        0.179054                0.012661
5    3496.736842      0.726639        0.179054                0.012661
6    4308.421053      0.682370        0.181120                0.012807
7    5120.105263      0.682370        0.181120                0.012807
8    5931.789474      0.682370        0.181120                0.012807
9    6743.473684      0.631133        0.198735                0.014053
10   7555.157895      0.650912        0.194416                0.013747
11   8366.842105      0.636791        0.200403                0.014171
12   9178.526316      0.636791        0.200403                0.014171
13   9990.210526      0.630476        0.195998                0.013859
14  10801.894737      0.630476        0.195998                0.013859
15  11613.578947      0.487381        0.197673                0.013978
16  12425.263158      0.487381        0.197673                0.013978
17  13236.947368      0.487381        0.197673                0.013978
18  14048.631579      0.487381        0.197673                0.013978
19  14860.315789      0.487381        0.197673                0.013978
20  15672.000000      0.487381        0.197673                0.013978</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">h2o.shutdown</span>(<span class="at">prompt =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>W tym przypadku możemy zaobserwować, że im klient bogatszy tym większa szansa na klasyfikację do grupy wiarygodnych kredytobiorców. Z kolei wraz ze wzrostem wysokości kredytu to prawdopodobieństwo maleje.</p>
<section id="zadania" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="zadania"><span class="header-section-number">3.3.1</span> Zadania</h3>
<ol type="1">
<li>Sprawdź jak model będzie się sprawdzał na danych, w których braki danych są traktowane jako osobna kategoria:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>credit_wna <span class="ot">&lt;-</span> credit <span class="sc">%&gt;%</span> <span class="fu">mutate_at</span>(<span class="fu">c</span>(<span class="st">"saving_accounts"</span>, <span class="st">"checking_account"</span>), fct_explicit_na)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Na podstawie charakterystyki <a href="http://www.wawrowski.edu.pl/data/sf_ny_homes.csv">mieszkań</a> przeprowadź klasyfikację ich umiejscowienia - San Francisco vs.&nbsp;New York.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>homes <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"http://www.wawrowski.edu.pl/data/sf_ny_homes.csv"</span>)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>homes <span class="ot">&lt;-</span> homes <span class="sc">%&gt;%</span> </span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">in_sf=</span><span class="fu">as.factor</span>(in_sf))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02-testy.html" class="pagination-link" aria-label="Testowanie hipotez">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Testowanie hipotez</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-regresja.html" class="pagination-link" aria-label="Regresja">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresja</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>