<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Metody przetwarzania i analizy danych w R - 4&nbsp; Regresja</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-grupowanie.html" rel="next">
<link href="./03-klasyfikacja.html" rel="prev">
<link href="./favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-regresja.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresja</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Metody przetwarzania i analizy danych w R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Wprowadzenie</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Analiza opisowa</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-testy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Testowanie hipotez</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-klasyfikacja.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Klasyfikacja</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-regresja.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresja</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-grupowanie.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Grupowanie</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Spis treści</h2>
   
  <ul>
  <li><a href="#wprowadzenie" id="toc-wprowadzenie" class="nav-link active" data-scroll-target="#wprowadzenie"><span class="header-section-number">4.1</span> Wprowadzenie</a></li>
  <li><a href="#regresja-prosta" id="toc-regresja-prosta" class="nav-link" data-scroll-target="#regresja-prosta"><span class="header-section-number">4.2</span> Regresja prosta</a>
  <ul class="collapse">
  <li><a href="#zadanie" id="toc-zadanie" class="nav-link" data-scroll-target="#zadanie"><span class="header-section-number">4.2.1</span> Zadanie</a></li>
  </ul></li>
  <li><a href="#regresja-wieloraka" id="toc-regresja-wieloraka" class="nav-link" data-scroll-target="#regresja-wieloraka"><span class="header-section-number">4.3</span> Regresja wieloraka</a>
  <ul class="collapse">
  <li><a href="#zadanie-1" id="toc-zadanie-1" class="nav-link" data-scroll-target="#zadanie-1"><span class="header-section-number">4.3.1</span> Zadanie</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regresja</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><a href="presentations/05_regresja.html">Prezentacja</a></p>
<section id="wprowadzenie" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="wprowadzenie"><span class="header-section-number">4.1</span> Wprowadzenie</h2>
<p>Metody regresji pozwalają na analizowanie zależności przyczynowo-skutkowych oraz predycję nieznanych wartości. Korzystając z tej metody należy jednak pamiętać, że model regresji jest tylko przybliżeniem rzeczywistości.</p>
<p>Przykłady zastosowania regresji:</p>
<ul>
<li><p>zależność wielkości sprzedaży od wydatków na reklamę</p></li>
<li><p>zależność wynagrodzenia od lat doświadczenia</p></li>
</ul>
<p>Na początku pracy wczytujemy biblioteki <em>tidyverse</em> i <em>readxl</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="regresja-prosta" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="regresja-prosta"><span class="header-section-number">4.2</span> Regresja prosta</h2>
<p>Na podstawie <a href="data/salary.xlsx">danych</a> dotyczących informacji o doświadczeniu i wynagrodzeniu pracowników zbuduj model określający ‘widełki’ dla potencjalnych pracowników o doświadczeniu równym 8, 10 i 11 lat.</p>
<p>Wczytujemy dane i sprawdzamy czy nie występują zera bądź braki danych z użyciem funkcji <code>summary()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>salary <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/salary.xlsx"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> YearsExperience      Salary      
 Min.   : 1.100   Min.   : 37731  
 1st Qu.: 3.200   1st Qu.: 56721  
 Median : 4.700   Median : 65237  
 Mean   : 5.313   Mean   : 76003  
 3rd Qu.: 7.700   3rd Qu.:100545  
 Max.   :10.500   Max.   :122391  </code></pre>
</div>
</div>
<p>Następnie stworzymy wykres.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(salary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresja_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Najprostszym sposobem wizualizacji jest wykorzystanie funkcji <code>plot()</code>, niemniej taki wykres nie jest najpiękniejszy i trudno się go formatuje. Dużo lepiej skorzystać z pakietu <code>ggplot2</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(salary, <span class="fu">aes</span>(<span class="at">x=</span>YearsExperience, <span class="at">y=</span>Salary)) <span class="sc">+</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Doświadczenie"</span>) <span class="sc">+</span> </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Pensja"</span>) <span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">35000</span>, <span class="dv">126000</span>) <span class="sc">+</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresja_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>W argumentach funkcji <code>ggplot()</code> podajemy co wizualizujemy, natomiast sposób prezentacji ustalany jest przez funkcje <code>geom</code>. Funkcje <code>xlab()</code> i <code>ylab()</code> określają etykiety osi, a <code>xlim()</code> i <code>ylim()</code> wartości graniczne. Funkcje rozpoczynające się od <code>theme_</code> określają wygląd wykresu.</p>
<p>Modelowanie rozpoczynamy od określenia zmiennej zależnej i niezależnej.</p>
<ul>
<li>zmienna zależna/objaśniana: pensja - <span class="math inline">\(y\)</span></li>
<li>zmienna niezależna/objaśniająca: doświadczenie - <span class="math inline">\(x\)</span></li>
</ul>
<p>Szukamy teraz wzoru na prostą opisującą badane cechy.</p>
<p>Ogólna postać regresji prostej jest następująca:</p>
<p><span class="math display">\[\hat{y}_{i}=b_{1}x_{i}+b_{0}\]</span></p>
<p>gdzie <span class="math inline">\(\hat{y}\)</span> oznacza wartość teoretyczną, leżącą na wyznaczonej prostej, <span class="math inline">\(x_i\)</span> wartość zmiennej niezależnej, a <span class="math inline">\(b_1\)</span> i <span class="math inline">\(b_0\)</span> to współczynniki modelu.</p>
<p>Wobec tego wartości empiryczne <span class="math inline">\(y\)</span> będą opisane formułą:</p>
<p><span class="math display">\[y_{i}=b_{1}x_{i}+b_{0}+u_{i}\]</span></p>
<p>w której <span class="math inline">\(u_i\)</span> oznacza składnik resztowy wyliczany jako <span class="math inline">\(u_{i}=y_{i}-\hat{y}_{i}\)</span>.</p>
<p><strong>Współczynnik kierunkowy</strong> <span class="math inline">\(b_1\)</span> informuje o ile przeciętne zmieni się wartość zmiennej objaśnianej <span class="math inline">\(y\)</span>, gdy wartość zmiennej objaśniającej <span class="math inline">\(x\)</span> wzrośnie o jednostkę.</p>
<p><strong>Wyraz wolny</strong> <span class="math inline">\(b_0\)</span> to wartość zmiennej objaśnianej <span class="math inline">\(y\)</span>, w sytuacji w której wartość zmiennej objaśniającej <span class="math inline">\(x\)</span> będzie równa 0. Często interpretacja tego parametru nie ma sensu.</p>
<p>Następnie w R korzystamy z funkcji <code>lm</code>, w której należy określić zależność funkcyjną w formie: <code>zmienna_zalezna ~ zmienna niezalezna</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>salary_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> Salary <span class="sc">~</span> YearsExperience, <span class="at">data =</span> salary)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(salary_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Salary ~ YearsExperience, data = salary)

Residuals:
    Min      1Q  Median      3Q     Max 
-7958.0 -4088.5  -459.9  3372.6 11448.0 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      25792.2     2273.1   11.35 5.51e-12 ***
YearsExperience   9450.0      378.8   24.95  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5788 on 28 degrees of freedom
Multiple R-squared:  0.957, Adjusted R-squared:  0.9554 
F-statistic: 622.5 on 1 and 28 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Na podstawie otrzymanego wyniku dokonujemy interpretacji parametrów.</p>
<ul>
<li>b1 = 9450 - wzrost doświadczenia o rok powoduje przeciętny wzrost pensji o 9450 $</li>
<li>b0 = 25792,2 - pracownik o doświadczeniu 0 lat uzyska pensję w wysokości 25792,2 $</li>
</ul>
<p>Trzy gwiazki przy współczynniku <span class="math inline">\(b_1\)</span> oznaczają, że doświadczenie ma istotny wpływ na wartości pensji. Wyraz wolny także jest istotny, natomiast ogólnie nie jest wymagana jesgo istotność.</p>
<p>Oprócz interpretacji współczynników ważne są jeszcze inne miary jakości modelu.</p>
<p><strong>Odchylenie standardowe składnika resztowego</strong> jest pierwiastkiem z sumy kwadratów reszt podzielonej przez liczbę obserwacji pomniejszoną o 2:</p>
<p><span class="math display">\[S_{u}=\sqrt{\frac{\sum\limits_{i=1}^{n}{(y_{i}-\hat{y}_{i})^2}}{n-2}}\]</span></p>
<p>Błąd resztowy (odchylenie standardowe składnika resztowego) <span class="math inline">\(S_u\)</span> wynosi 5788<span class="math inline">\(, co oznacza, że wartości obliczone na podstawie modelu różnią się od rzeczywistości średnio o +/- 5788\)</span></p>
<p><strong>Współczynnik determinacji</strong> określa, jaki procent wariancji zmiennej objaśnianej został wyjaśniony przez funkcję regresji. <span class="math inline">\(R^2\)</span> przyjmuje wartości z przedziału <span class="math inline">\(&lt;0;1&gt;\)</span> ( <span class="math inline">\(&lt;0\%;100\%&gt;\)</span> ), przy czym model regresji tym lepiej opisuje zachowanie się badanej zmiennej objaśnianej, im <span class="math inline">\(R^2\)</span> jest bliższy jedności (bliższy 100%)</p>
<p><span class="math display">\[R^2=1-\frac{\sum\limits_{i=1}^{n}{(y_{i}-\hat{y}_{i})^2}}{\sum\limits_{i=1}^{n}{(y_{i}-\bar{y}_{i})^2}}\]</span></p>
<p>Współczynnik <span class="math inline">\(R^2\)</span> (multiple R-squared) wynosi 0,957 czyli doświadczenie wyjaśnia 95,7% zmienności pensji</p>
<p>Na podstawie tego modelu dokonamy wyznaczenia wartości teoretycznych dla kilku wybranych wartości doświadczenia. Nowe wartości muszą być w postaci zbioru danych, zatem tworzymy nową ramkę danych.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>nowiPracownicy <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">YearsExperience=</span><span class="fu">c</span>(<span class="dv">8</span>,<span class="dv">10</span>,<span class="dv">11</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(salary_model, nowiPracownicy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3 
101391.9 120291.8 129741.8 </code></pre>
</div>
</div>
<p>Tym sposobem uzyskujemy następujące widełki:</p>
<ul>
<li>pracownik o 8 latach doświadczenia - proponowana pensja 101391,9 $ +/- 5788 $</li>
<li>pracownik o 10 latach doświadczenia - proponowana pensja 120291,8 $ +/- 5788 $</li>
<li>pracownik o 11 latach doświadczenia - proponowana pensja 129741,8 $ +/- 5788 $</li>
</ul>
<p>W powyższym przykładzie prognozowane wartości pojawiły się w konsoli, natomiast w sytuacji, w której chcielibyśmy wykonać predykcję dla bardzo wielu nowych wartości to warto te prognozowane wartości umieścić od razu w zbiorze danych. Można to zrobić w następujący sposób:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>nowiPracownicy <span class="ot">&lt;-</span> nowiPracownicy <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">salary_pred=</span><span class="fu">predict</span>(<span class="at">object =</span> salary_model, <span class="at">newdata =</span> .))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>nowiPracownicy</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  YearsExperience salary_pred
1               8    101391.9
2              10    120291.8
3              11    129741.8</code></pre>
</div>
</div>
<p>W powyższym kodzie symbol <code>.</code> oznacza analizowany zbiór danych, zatem nie ma potrzeby powtarzania jego nazwy.</p>
<section id="zadanie" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="zadanie"><span class="header-section-number">4.2.1</span> Zadanie</h3>
<p>Dla danych dotyczących <a href="data/sklep77.xlsx">sklepu nr 77</a> opracuj model zależności sprzedaży od liczby klientów. Ile wynosi teoretyczna sprzedaż w dniach, w których liczba klientów będzie wynosiła 560, 740, 811 oraz 999 osób?</p>
</section>
</section>
<section id="regresja-wieloraka" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="regresja-wieloraka"><span class="header-section-number">4.3</span> Regresja wieloraka</h2>
<p>Ogólna postać regresji wielorakiej jest następująca:</p>
<p><span class="math display">\[\hat{y}_{i}=b_{1}x_{1i}+b_{2}x_{2i}+...+b_{k}x_{ki}+b_{0}\]</span></p>
<p>W tym przypadku nie wyznaczamy prostej tylko <span class="math inline">\(k\)</span>-wymiarową przestrzeń.</p>
<p>Na podstawie danych dotyczących <a href="data/pracownicy.xlsx">zatrudnienia</a> opracuj model, w którym zmienną zależną jest bieżące wynagrodzenie. Za pomocą regresji określimy jakie cechy mają istotny wpływ na to wynagrodzenie.</p>
<p>Opis zbioru:</p>
<ul>
<li>id - kod pracownika</li>
<li>plec - płeć pracownika (0 - mężczyzna, 1 - kobieta)</li>
<li>data_urodz - data urodzenia</li>
<li>edukacja - wykształcenie (w latach nauki)</li>
<li>kat_pracownika - grupa pracownicza (1 - specjalista, 2 - menedżer, 3 - konsultant)</li>
<li>bwynagrodzenie - bieżące wynagrodzenie</li>
<li>pwynagrodzenie - początkowe wynagrodzenie</li>
<li>staz - staż pracy (w miesiącach)</li>
<li>doswiadczenie - poprzednie zatrudnienie (w miesiącach)</li>
<li>zwiazki - przynależność do związków zawodowych (0 - nie, 1 - tak)</li>
<li>wiek - wiek (w latach)</li>
</ul>
<p>Rozpoczynamy od wczytania danych,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>pracownicy <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/pracownicy.xlsx"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>pracownicy2 <span class="ot">&lt;-</span> pracownicy <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(wiek)) <span class="sc">%&gt;%</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>id, <span class="sc">-</span>data_urodz) <span class="sc">%&gt;%</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">plec=</span><span class="fu">as.factor</span>(plec),</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">kat_pracownika=</span><span class="fu">as.factor</span>(kat_pracownika),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">zwiazki=</span><span class="fu">as.factor</span>(zwiazki))</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pracownicy2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> plec       edukacja     kat_pracownika bwynagrodzenie   pwynagrodzenie 
 0:257   Min.   : 8.00   1:362          Min.   : 15750   Min.   : 9000  
 1:216   1st Qu.:12.00   2: 27          1st Qu.: 24000   1st Qu.:12450  
         Median :12.00   3: 84          Median : 28800   Median :15000  
         Mean   :13.49                  Mean   : 34418   Mean   :17009  
         3rd Qu.:15.00                  3rd Qu.: 37050   3rd Qu.:17490  
         Max.   :21.00                  Max.   :135000   Max.   :79980  
      staz       doswiadczenie    zwiazki      wiek      
 Min.   :63.00   Min.   :  0.00   0:369   Min.   :24.00  
 1st Qu.:72.00   1st Qu.: 19.00   1:104   1st Qu.:30.00  
 Median :81.00   Median : 55.00           Median :33.00  
 Mean   :81.14   Mean   : 95.95           Mean   :38.67  
 3rd Qu.:90.00   3rd Qu.:139.00           3rd Qu.:47.00  
 Max.   :98.00   Max.   :476.00           Max.   :66.00  </code></pre>
</div>
</div>
<p>W zmiennej wiek występował brak danych, który został usunięty. Usunięto także kolumny, które nie przydadzą się w modelowaniu. Ponadto dokonujemy przekształcenia typu cech, które są jakościowe (płeć, kat_pracownika, zwiazki) z typu liczbowego na czynnik/faktor. Taka modyfikacja powoduje, że ta cecha będzie przez model traktowana jako zmienna dychotomiczna (zerojedynkowa). Proces trasformacji takiej cechy jest pokazany poniżej.</p>
<p>Oryginalny zbiór</p>
<table class="table">
<thead>
<tr class="header">
<th>id</th>
<th>stanowisko</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>specjalista</td>
</tr>
<tr class="even">
<td>2</td>
<td>menedżer</td>
</tr>
<tr class="odd">
<td>3</td>
<td>specjalista</td>
</tr>
<tr class="even">
<td>4</td>
<td>konsultant</td>
</tr>
<tr class="odd">
<td>5</td>
<td>konsultant</td>
</tr>
</tbody>
</table>
<p>Zmienna zerojedynkowa</p>
<table class="table">
<thead>
<tr class="header">
<th>id</th>
<th>menedżer</th>
<th>konsultant</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>2</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>4</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td>5</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>W modelu zmienna zależna to <code>bwynagrodzenie</code>, natomiast jako zmienne niezależne bierzemy pod uwagę wszystkie pozostałe cechy. W celu uniknięcia notacji naukowej w uzyskiwanych wynikach dodajemy opcję <code>options(scipen = 5)</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">5</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(bwynagrodzenie <span class="sc">~</span> ., pracownicy2)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bwynagrodzenie ~ ., data = pracownicy2)

Residuals:
   Min     1Q Median     3Q    Max 
-23185  -3041   -705   2591  46295 

Coefficients:
                   Estimate  Std. Error t value Pr(&gt;|t|)    
(Intercept)     -4764.87418  3590.49652  -1.327  0.18514    
plec1           -1702.43743   796.51779  -2.137  0.03309 *  
edukacja          482.43603   160.83977   2.999  0.00285 ** 
kat_pracownika2  6643.17910  1638.06138   4.056 5.87e-05 ***
kat_pracownika3 11169.64519  1372.73990   8.137 3.77e-15 ***
pwynagrodzenie      1.34021     0.07317  18.315  &lt; 2e-16 ***
staz              154.50876    31.65933   4.880 1.46e-06 ***
doswiadczenie     -15.77375     5.78369  -2.727  0.00663 ** 
zwiazki1        -1011.55276   787.80884  -1.284  0.19978    
wiek              -64.78787    47.88015  -1.353  0.17668    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6809 on 463 degrees of freedom
Multiple R-squared:  0.8444,    Adjusted R-squared:  0.8414 
F-statistic: 279.1 on 9 and 463 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Tak zbudowany model wyjaśnia 84,4% zmienności bieżącego wynagrodzenia, ale nie wszystkie zmienne są w tym modelu istotne.</p>
<p>Parametry regresji mają następujące interpretacje:</p>
<ul>
<li>plec1 - kobiety zarabiają przeciętnie o 1702,44 zł mniej niż mężczyźni,</li>
<li>edukacja - wzrost liczby lat nauki o rok powoduje średni wzrost bieżącego wynagrodzenia o 482,44 zł</li>
<li>kat_pracownika2 - pracownicy o kodzie 2 (menedżer) zarabiają średnio o 6643,18 zł więcej niż pracownik o kodzie 1 (specjalista)</li>
<li>kat_pracownika2 - pracownicy o kodzie 3 (konsultant) zarabiają średnio o 11169,65 zł więcej niż pracownik o kodzie 1 (specjalista)</li>
<li>pwynagrodzenie - wzrost początkowego wynagrodzenia o 1 zł powoduje przeciętny wzrost bieżącego wynagrodzenia o 1,34 zł</li>
<li>staz - wzrost stażu pracy o miesiąc skutkuje przeciętnym wzrostem bieżącego wynagrodzenia o 154,51 zł</li>
<li>doswiadcznie - wzrost doświadczenia o miesiąc powoduje średni spadek bieżącego wynagrodzenia o 15,77 zł</li>
<li>zwiazki1 - pracownicy należący do związków zawodowych zarabiają średnio o 1011,55 zł mniej aniżeli pracownicy, którzy do związków nie zależą</li>
<li>wiek - wzrost wieku pracownika o 1 rok to przeciętnym spadek bieżącego wynagrodzenia o 64,79 zł</li>
</ul>
<p>Wszystkie te interpretacje obowiązują przy założeniu <em>ceteris paribus</em> - przy pozostałych warunkach niezmienionych.</p>
<p>Ten model wymaga oczywiście ulepszenia do czego wykorzystamy pakiet <a href="https://cran.r-project.org/web/packages/olsrr/index.html">olsrr</a>.</p>
<p>Pierwszą kwestią, którą się zajmiemy jest współliniowość zmiennych. W regresji zmienne objaśniające powinny być jak najbardziej skorelowane ze zmienną objaśnianą, a możliwie nieskorelowane ze sobą. W związku z tym wybieramy ze zbioru wyłącznie cechy ilościowe, dla którym wyznaczymy współczynnik korelacji liniowej Pearsona. Do wizualizacji tych wartości wykorzystamy pakiet <a href="https://cran.r-project.org/web/packages/corrplot/">corrplot</a> służący do wizualizacji współczynnika korelacji.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(olsrr)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>korelacje <span class="ot">&lt;-</span> pracownicy2 <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(plec, kat_pracownika, zwiazki)) <span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>()</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(korelacje, <span class="at">method =</span> <span class="st">"number"</span>, <span class="at">type =</span> <span class="st">"upper"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresja_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Możemy zauważyć, że wartości bieżącego wynagrodzenia są najsilniej skorelowane w wartościami wynagrodzenia początkowego. Także doświadczenie i wiek są silnie ze sobą związane, co może sugerować, że obie zmienne wnoszą do modelu podobną informację.</p>
<p>W związku z tym powinniśmy wyeliminować niektóre zmienne z modelu pozostawiając te najważniejsze. Wyróżnia się trzy podejścia do tego zagadnienia:</p>
<ul>
<li>ekspercki dobór cech,</li>
<li>budowa wszystkich możliwych modeli i wybór najlepszego według określonego kryterium,</li>
<li>regresja krokowa.</li>
</ul>
<p>W przypadku budowy wszystkich możliwych modeli należy pamiętać o rosnącej wykładniczo liczbie modeli: <span class="math inline">\(2^p-1\)</span>, gdzie <span class="math inline">\(p\)</span> oznacza liczbę zmiennych objaśniających. w rozważanym przypadku liczba modeli wynosi 255.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>wszystkie_modele <span class="ot">&lt;-</span> <span class="fu">ols_step_all_possible</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>W uzyskanym zbiorze danych są informacje o numerze modelu, liczbie użytych zmiennych, nazwie tych zmiennych oraz wiele miar jakości. Te, które warto wziąć pod uwagę to przede wszystkim:</p>
<ul>
<li><code>rsquare</code> - współczynnik R-kwadrat,</li>
<li><code>aic</code> - kryterium informacyjne Akaike,</li>
<li><code>msep</code> - błąd średniokwadratowy predykcji.</li>
</ul>
<p>Najwyższa wartość współczynnika <span class="math inline">\(R^2\)</span> związana jest z modelem zawierającym wszystkie dostępne zmienne objaśniające. Jest to pewna niedoskonałość tej miary, która rośnie wraz z liczbą zmiennych w modelu, nawet jeśli te zmienne nie są istotne.</p>
<p>W przypadku kryteriów informacyjnych oraz błędu średniokwadratowego interesują nas jak najmniejsze wartości. Wówczas jako najlepszy należy wskazać model nr 219 zawierający 6 zmiennych objaśniających.</p>
<p>Metodą, która także pozwoli uzyskać optymalny model, ale przy mniejszym obciążeniu obliczeniowym jest regresja krokowa polegająca na krokowym budowaniu modelu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ols_step_both_aic</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                                    Stepwise Summary                                    
--------------------------------------------------------------------------------------
Step    Variable                 AIC          SBC         SBIC        R2       Adj. R2 
--------------------------------------------------------------------------------------
 0      Base Model            10565.472    10573.790    9220.060    0.00000    0.00000 
 1      pwynagrodzenie (+)     9862.260     9874.737    8518.596    0.77484    0.77436 
 2      kat_pracownika (+)     9786.152     9806.947    8440.801    0.80992    0.80870 
 3      doswiadczenie (+)      9743.487     9768.441    8398.512    0.82705    0.82557 
 4      staz (+)               9719.469     9748.582    8374.863    0.83630    0.83455 
 5      edukacja (+)           9707.338     9740.610    8363.030    0.84112    0.83907 
 6      plec (+)               9703.188     9740.620    8359.065    0.84317    0.84081 
--------------------------------------------------------------------------------------

Final Model Output 
------------------

                             Model Summary                              
-----------------------------------------------------------------------
R                          0.918       RMSE                   6762.202 
R-Squared                  0.843       MSE                46514089.581 
Adj. R-Squared             0.841       Coef. Var                19.815 
Pred R-Squared             0.837       AIC                    9703.188 
MAE                     4418.325       SBC                    9740.620 
-----------------------------------------------------------------------
 RMSE: Root Mean Square Error 
 MSE: Mean Square Error 
 MAE: Mean Absolute Error 
 AIC: Akaike Information Criteria 
 SBC: Schwarz Bayesian Criteria 

                                      ANOVA                                        
----------------------------------------------------------------------------------
                        Sum of                                                    
                       Squares         DF        Mean Square       F         Sig. 
----------------------------------------------------------------------------------
Regression    116287161827.859          7    16612451689.694    357.149    0.0000 
Residual       21629051655.016        465       46514089.581                      
Total         137916213482.875        472                                         
----------------------------------------------------------------------------------

                                         Parameter Estimates                                           
------------------------------------------------------------------------------------------------------
          model         Beta    Std. Error    Std. Beta      t        Sig          lower        upper 
------------------------------------------------------------------------------------------------------
    (Intercept)    -6547.147      3402.860                 -1.924    0.055    -13234.036      139.741 
 pwynagrodzenie        1.342         0.073        0.618    18.382    0.000         1.198        1.485 
kat_pracownika2     6734.992      1631.122        0.092     4.129    0.000      3529.708     9940.275 
kat_pracownika3    11226.635      1368.413        0.251     8.204    0.000      8537.596    13915.674 
  doswiadczenie      -22.302         3.571       -0.137    -6.246    0.000       -29.318      -15.285 
           staz      147.865        31.461        0.087     4.700    0.000        86.041      209.689 
       edukacja      501.391       160.270        0.085     3.128    0.002       186.447      816.335 
          plec1    -1878.949       761.703       -0.055    -2.467    0.014     -3375.755     -382.143 
------------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>Otrzymany w ten sposób model jest tożsamy z modelem charakteryzującym się najlepszymi miarami jakości spośród zbioru wszystkich możliwych modeli:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>wybrany_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(bwynagrodzenie <span class="sc">~</span> pwynagrodzenie <span class="sc">+</span> kat_pracownika <span class="sc">+</span> doswiadczenie <span class="sc">+</span> staz <span class="sc">+</span> plec <span class="sc">+</span> edukacja, <span class="at">data =</span> pracownicy2)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wybrany_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bwynagrodzenie ~ pwynagrodzenie + kat_pracownika + 
    doswiadczenie + staz + plec + edukacja, data = pracownicy2)

Residuals:
   Min     1Q Median     3Q    Max 
-22922  -3300   -673   2537  46524 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     -6547.147   3402.860  -1.924  0.05496 .  
pwynagrodzenie      1.342      0.073  18.382  &lt; 2e-16 ***
kat_pracownika2  6734.992   1631.122   4.129 4.32e-05 ***
kat_pracownika3 11226.635   1368.413   8.204 2.30e-15 ***
doswiadczenie     -22.302      3.571  -6.246 9.51e-10 ***
staz              147.865     31.461   4.700 3.43e-06 ***
plec1           -1878.949    761.703  -2.467  0.01399 *  
edukacja          501.391    160.270   3.128  0.00187 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6820 on 465 degrees of freedom
Multiple R-squared:  0.8432,    Adjusted R-squared:  0.8408 
F-statistic: 357.1 on 7 and 465 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Uzyskany model charakteryzuje się nieznacznie większym błędem resztowym od modelu ze wszystkimi zmiennymi, ale wszystkie zmienne są istotne. Wyraz wolny <code>(Intercept)</code> nie musi być istotny w modelu.</p>
<p>Wróćmy jeszcze na chwilę do tematu współliniowości zmiennych objaśniających:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ols_vif_tol</span>(wybrany_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Variables Tolerance      VIF
1  pwynagrodzenie 0.2979792 3.355939
2 kat_pracownika2 0.6867111 1.456217
3 kat_pracownika3 0.3595692 2.781106
4   doswiadczenie 0.7054176 1.417600
5            staz 0.9862198 1.013973
6           plec1 0.6831049 1.463904
7        edukacja 0.4607529 2.170361</code></pre>
</div>
</div>
<p>Współczynnik tolerancji wskazuje na procent niewyjaśnionej zmienności danej zmiennej przez pozostałe zmienne objaśniające. Przykładowo współczynnik tolerancji dla początkowego wynagrodzenia wynosi 0,2980, co oznacza, że 30% zmienności początkowego wynagrodzenia nie jest wyjaśnione przez pozostałe zmienne w modelu. Z kolei współczynnik VIF jest obliczany na podstawie wartości współczynnika tolerancji i wskazuje o ile wariancja szacowanego współczynnika regresji jest podwyższona z powodu współliniowości danej zmiennej objaśniającej z pozostałymi zmiennymi objaśniającymi. Wartość współczynnika VIF powyżej 4 należy uznać za wskazującą na współliniowość. W analizowanym przypadku takie zmienne nie występują.</p>
<p>Ocena siły wpływu poszczególnych zmiennych objaśniających na zmienną objaśnianą w oryginalnej postaci modelu nie jest możliwa. Należy wyznaczyć standaryzowane współczynniki beta, które wyliczane są na danych standaryzowanych, czyli takich, które są pozbawione jednostek i cechują się średnią równą 0, a odchyleniem standardowym równym 1. Standaryzacja ma sens tylko dla cech numerycznych, w związku z czym korzystamy z funkcji <code>mutate_if()</code>, która jako pierwszy argument przyjmuje warunek, który ma być spełniony, aby była zastosowane przekształcenie podawane jako drugi argument.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>pracownicy2_std <span class="ot">&lt;-</span> pracownicy2 <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.numeric, scale)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>wybrany_model_std <span class="ot">&lt;-</span> <span class="fu">lm</span>(bwynagrodzenie <span class="sc">~</span> pwynagrodzenie <span class="sc">+</span> kat_pracownika <span class="sc">+</span> </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>                          doswiadczenie <span class="sc">+</span> staz <span class="sc">+</span> plec <span class="sc">+</span> edukacja, <span class="at">data =</span> pracownicy2_std)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wybrany_model_std)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bwynagrodzenie ~ pwynagrodzenie + kat_pracownika + 
    doswiadczenie + staz + plec + edukacja, data = pracownicy2_std)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.34098 -0.19306 -0.03939  0.14841  2.72171 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     -0.08893    0.03144  -2.828  0.00488 ** 
pwynagrodzenie   0.61842    0.03364  18.382  &lt; 2e-16 ***
kat_pracownika2  0.39400    0.09542   4.129 4.32e-05 ***
kat_pracownika3  0.65677    0.08005   8.204 2.30e-15 ***
doswiadczenie   -0.13657    0.02187  -6.246 9.51e-10 ***
staz             0.08691    0.01849   4.700 3.43e-06 ***
plec1           -0.10992    0.04456  -2.467  0.01399 *  
edukacja         0.08464    0.02706   3.128  0.00187 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.399 on 465 degrees of freedom
Multiple R-squared:  0.8432,    Adjusted R-squared:  0.8408 
F-statistic: 357.1 on 7 and 465 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Spośród cech ilościowych największy wpływ na zmienną objaśnianą mają wartości wynagrodzenia początkowego, staż, edukacja i na końcu doświadczenie.</p>
<p>Reszty czyli różnice pomiędzy obserwowanymi wartościami zmiennej objaśnianej, a wartościami wynikającymi z modelu w klasycznej metodzie najmniejszych kwadratów powinny być zbliżone do rozkładu normalnego. Oznacza to, że najwięcej reszt powinno skupiać się wokół zerowych różnic, natomiast jak najmniej powinno być wartości modelowych znacznie różniących się od tych rzeczywistych.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ols_plot_resid_hist</span>(wybrany_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresja_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Reszty w naszym modelu wydają się być zbliżone do rozkładu normalnego. Jednoznaczną odpowiedź da jednak odpowiedni test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ols_test_normality</span>(wybrany_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>-----------------------------------------------
       Test             Statistic       pvalue  
-----------------------------------------------
Shapiro-Wilk              0.868          0.0000 
Kolmogorov-Smirnov        0.1092         0.0000 
Cramer-von Mises         42.5504         0.0000 
Anderson-Darling         13.0233         0.0000 
-----------------------------------------------</code></pre>
</div>
</div>
<p>Hipoteza zerowa w tych testach mówi o zgodności rozkładu reszt z rozkładem normalnym. Na podstawie wartości p, które są mniejsze od <span class="math inline">\(\alpha=0,05\)</span> stwierdzamy, że są podstawy do odrzucenia tej hipotezy czyli reszty z naszego modelu nie mają rozkładu normalnego. W diagnostyce przyczyn takiego stanu rzeczy pomoże nam wykres kwantyl-kwantyl:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ols_plot_resid_qq</span>(wybrany_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresja_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Gdyby wszystkie punkty leżały na prostej to oznaczałoby to normalność rozkładu reszt. Tymczasem po lewej i prawej stronie tego wykresu znajdują się potencjalne wartości odstające, które znacznie wpływają na rozkład reszt modelu.</p>
<p>Wartości odstające można ustalić na podstawie wielu kryteriów. Do jednych z najbardziej popularnych należy odległość Cooka:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>cook <span class="ot">&lt;-</span> <span class="fu">ols_plot_cooksd_bar</span>(wybrany_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresja_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Przypisanie tej funkcji do obiektu zwraca nam tabelę z numerami zidentyfikowanych obserwacji wpływowych. W przypadku odległości Cooka jest to 35 obserwacji. Granica przynależności do grupy wartości odstających jest wyznaczana według wzoru: <span class="math inline">\(4/n\)</span>, gdzie <span class="math inline">\(n\)</span> to liczba wszystkich obserwacji.</p>
<p>Inną miarą są reszty studentyzowane.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>stud3 <span class="ot">&lt;-</span> <span class="fu">ols_plot_resid_stud</span>(wybrany_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresja_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Wyżej wykorzystana funkcja jako kryterium odstawania przyjmuje wartość 3 identyfikując 10 obserwacji wpływowych. Z kolei dodanie do powyższej funkcji przyrostka <em>fit</em> powoduje przyjęcie jako granicy wartości równej 2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>stud2 <span class="ot">&lt;-</span> <span class="fu">ols_plot_resid_stud_fit</span>(wybrany_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresja_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>W ten sposób zostało zidentyfikowanych 22 obserwacji odstających. Korzystając z odległości Cooka wyeliminujemy obserwacje odstające ze zbioru:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> cook<span class="sc">$</span>data<span class="sc">$</span>obs[cook<span class="sc">$</span>data<span class="sc">$</span>color <span class="sc">==</span> <span class="st">"outlier"</span>]</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>pracownicy_out <span class="ot">&lt;-</span> pracownicy2[<span class="sc">-</span>outliers,]</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>wybrany_model_out <span class="ot">&lt;-</span> <span class="fu">lm</span>(bwynagrodzenie <span class="sc">~</span> pwynagrodzenie <span class="sc">+</span> kat_pracownika <span class="sc">+</span> doswiadczenie <span class="sc">+</span> staz <span class="sc">+</span> plec <span class="sc">+</span> edukacja, </span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> pracownicy_out)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wybrany_model_out)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bwynagrodzenie ~ pwynagrodzenie + kat_pracownika + 
    doswiadczenie + staz + plec + edukacja, data = pracownicy_out)

Residuals:
     Min       1Q   Median       3Q      Max 
-12591.2  -2696.4   -564.8   2263.0  14704.1 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     -3756.8288  2381.5361  -1.577 0.115420    
pwynagrodzenie      1.3696     0.0676  20.260  &lt; 2e-16 ***
kat_pracownika2  6480.6971  1049.9539   6.172 1.56e-09 ***
kat_pracownika3  9791.5000  1059.4980   9.242  &lt; 2e-16 ***
doswiadczenie     -18.5808     2.3229  -7.999 1.17e-14 ***
staz              116.3809    20.9704   5.550 5.01e-08 ***
plec1           -1616.6030   505.1391  -3.200 0.001475 ** 
edukacja          397.7652   105.8146   3.759 0.000194 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4271 on 430 degrees of freedom
Multiple R-squared:  0.894, Adjusted R-squared:  0.8923 
F-statistic: 518.3 on 7 and 430 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Model dopasowany na takim zbiorze charakteryzuje się dużo mniejszym błędem standardowym oraz wyższym współczynnikiem <span class="math inline">\(R^2\)</span> w porównaniu do poprzedniego. Sprawdźmy w takim razie normalność reszt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ols_plot_resid_qq</span>(wybrany_model_out)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regresja_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Wykres kwantyl-kwantyl wygląda już dużo lepiej i w zasadzie nie obserwuje tu się dużych odstępstw od rozkładu normalnego. Przeprowadźmy jeszcze odpowiednie testy statystyczne.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ols_test_normality</span>(wybrany_model_out)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>-----------------------------------------------
       Test             Statistic       pvalue  
-----------------------------------------------
Shapiro-Wilk              0.9696         0.0000 
Kolmogorov-Smirnov        0.0667         0.0405 
Cramer-von Mises         38.1644         0.0000 
Anderson-Darling          3.5421         0.0000 
-----------------------------------------------</code></pre>
</div>
</div>
<p>Tylko test Kołmogorova-Smirnova na poziomie istotności <span class="math inline">\(\alpha=0,01\)</span> wskazał na brak podstaw do odrzucenia hipotezy zerowej.</p>
<section id="zadanie-1" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="zadanie-1"><span class="header-section-number">4.3.1</span> Zadanie</h3>
<p>Na podstawie zbioru dotyczącego <a href="data/startups.xlsx">50 startupów</a> określ jakie czynniki wpływają na przychód startupów.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>startupy <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">"data/startups.xlsx"</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>startupy <span class="ot">&lt;-</span> janitor<span class="sc">::</span><span class="fu">clean_names</span>(startupy)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(startupy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   r_d_spend      administration   marketing_spend     state          
 Min.   :     0   Min.   : 51283   Min.   :     0   Length:50         
 1st Qu.: 39936   1st Qu.:103731   1st Qu.:129300   Class :character  
 Median : 73051   Median :122700   Median :212716   Mode  :character  
 Mean   : 73722   Mean   :121345   Mean   :211025                     
 3rd Qu.:101603   3rd Qu.:144842   3rd Qu.:299469                     
 Max.   :165349   Max.   :182646   Max.   :471784                     
     profit      
 Min.   : 14681  
 1st Qu.: 90139  
 Median :107978  
 Mean   :112013  
 3rd Qu.:139766  
 Max.   :192262  </code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-klasyfikacja.html" class="pagination-link" aria-label="Klasyfikacja">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Klasyfikacja</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-grupowanie.html" class="pagination-link" aria-label="Grupowanie">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Grupowanie</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>